# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "retrospec-foreman_plugin"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Corey Osman"]
  s.date = "2015-10-01"
  s.description = "Automates the creation of foreman plugins"
  s.email = "corey@logicminds.biz"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    "DEVELOPMENT.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/retrospec-foreman_plugin.rb",
    "lib/retrospec/plugins/v1/plugin/foreman_helpers.rb",
    "lib/retrospec/plugins/v1/plugin/foreman_plugin.rb",
    "lib/retrospec/plugins/v1/plugin/spec_object.rb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/.gitignore",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/.rubocop.yml",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/.rubocop_todo.yml",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/.tx/config",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/DEVELOPMENT.md.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/Gemfile",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/LICENSE",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/README.md.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/Rakefile.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/app/controllers/.gitkeep",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/app/controllers/foreman_plugin_template/hosts_controller.rb.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/app/helpers/.gitkeep",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/app/helpers/concerns/foreman_plugin_template/hosts_helper_extensions.rb.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/app/mailers/.gitkeep",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/app/models/.gitkeep",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/app/models/concerns/foreman_plugin_template/host_extensions.rb.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/app/overrides/dashboard/index/sample_override.html.erb.deface",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/app/views/.gitkeep",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/app/views/dashboard/_foreman_plugin_template_widget.html.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/app/views/foreman_plugin_template/hosts/new_action.html.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/app/views/foreman_plugin_template/layouts/new_layout.html.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/config/routes.rb.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/foreman_plugin_template.gemspec.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/lib/foreman_plugin_template.rb.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/lib/foreman_plugin_template/engine.rb.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/lib/foreman_plugin_template/version.rb.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/lib/tasks/foreman_plugin_template_tasks.rake.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/locale/Makefile.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/locale/en/foreman_plugin_template.po.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/locale/foreman_plugin_template.pot.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/locale/gemspec.rb.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/test/factories/foreman_plugin_template_factories.rb.retrospec.erb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/test/test_plugin_helper.rb",
    "lib/retrospec/plugins/v1/plugin/templates/module_files/test/unit/foreman_plugin_template_test.rb.retrospec.erb",
    "rename_templates.rb",
    "retrospec-foreman_plugin.gemspec",
    "spec/foreman_helpers_spec.rb",
    "spec/plugin_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/nwops/retrospec-foreman_plugin"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "Automates the creation of foreman plugins"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<retrospec>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.2"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
    else
      s.add_dependency(%q<retrospec>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 3.2"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
    end
  else
    s.add_dependency(%q<retrospec>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 3.2"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
  end
end

